[package]
name = "interflow-coreaudio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
interflow-core.workspace = true

coreaudio-rs = "0.14.1"
coreaudio-sys = "0.2.17"
log.workspace = true
thiserror.workspace = true
oneshot = { version = "0.2.1", features = ["std"] }
