on: # rebuild any PRs and main branch changes
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main

name: bloat

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust 1.80.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.80.0
          default: true
          override: true
      - name: Install dependencies
        run: sudo apt install libasound2-dev
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}