name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (Linux)
      run: sudo apt install libasound2-dev
    - name: Install Rust 1.85
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.85
        default: true
        override: true
        components: rustfmt
    - name: Run rustfmt
      run: cargo fmt -- --check
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [1.83, 1.84, 1.85]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (Linux)
      if: ${{matrix.os == 'ubuntu-latest' }}
      run: sudo apt install libasound2-dev
    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        default: true
        override: true
        components: clippy
    - uses: LoliGothick/clippy-check@master
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run clippy
      uses: clechasseur/rs-clippy-check@v4
      with:
        args: --all-features
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
