name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install dependencies (Linux)
      run: sudo apt install libasound2-dev libspa-0.2-dev libpipewire-0.3-dev
    - name: Install Rust 1.88
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.88
        default: true
        override: true
        components: rustfmt
    - name: Run rustfmt
      run: cargo fmt -- --check
  clippy:
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu' }}
        run: sudo apt install libasound2-dev libspa-0.2-dev libpipewire-0.3-dev
      - name: Install Rust 1.88
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88
          default: true
          override: true
          components: clippy
      - uses: LoliGothick/clippy-check@master
        continue-on-error: true
        with:
          options: ${{ matrix.os == 'ubuntu' && '--features pipewire' || '' }}
          token: ${{ secrets.GITHUB_TOKEN }}
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [1.85, 1.86, 1.87, 1.88]
        feature-pipewire: [false, true]
        exclude:
          - os: windows-latest
            feature-pipewire: true
          - os: macos-latest
            feature-pipewire: true
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Install dependencies (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install libasound2-dev libspa-0.2-dev libpipewire-0.3-dev
    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        default: true
        override: true
    - name: Build
      run: cargo build --verbose ${{ matrix.feature-pipewire && '--features pipewire' || '' }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.feature-pipewire && '--features pipewire' || '' }}
